#include <stdio.h>
#include <cs50.h>
#include <math.h>
#include <stdlib.h>
// Finding the cards length and make
int lengthCheck();
char *cardCheck();
long firstTwoNumbers();
int *extractDigits();
int *extractSeconds();
int obtainDispersionLength();
int *SetIntDefaultValues();
long *SetLongDefaultValues();
int *separateDigits();
// grabs each other digit starting from a base index
int *secondObt(int cardLength, int *individualDigitss, int startIDX, bool doubleNums)
{
    //0034227
    //5 0 1 6 2 8 8 3
    // grab the length of every secodn one, and set each index of the array to -999
    int length = obtainDispersionLength(startIDX, cardLength);
    int *digits = SetIntDefaultValues(length);

    for (int i = startIDX, pos = 0; i < cardLength; i += 2, pos++)
    {
        digits[pos] = individualDigitss[i];
        if (doubleNums)
        {
            digits[pos] *= 2;
        }
    }
    return digits;
}
int main()
{

    long cardNumber;
    cardNumber = get_long_long("Card Number: ");
    int cardLength = lengthCheck(cardNumber);
    while (cardLength < 2)
    {
        cardNumber = get_long_long("Card Number: ");
        cardLength = lengthCheck(cardNumber);
    }
    long firstTwo = firstTwoNumbers(cardNumber, cardLength);
    char *cardType = cardCheck(cardLength, firstTwo);

    int *individualDigits = extractDigits(cardLength, cardNumber);
    int *everySecondFromSecond = secondObt(cardLength, individualDigits, 1, true);
    everySecondFromSecond = separateDigits(everySecondFromSecond);
    int *everySecondFromFirst = secondObt(cardLength, individualDigits, 0, false);
    everySecondFromFirst = separateDigits(everySecondFromFirst);
    int sum = 0;
    for (int i = 0; everySecondFromSecond[i] != -999; i++)
    {
        sum += everySecondFromSecond[i];
    }
    for (int j = 0; everySecondFromFirst[j] != -999; j++)
    {
        sum += everySecondFromFirst[j];
    }
    if (sum % 10 == 0)
    {
        printf("%s", cardType);
    }
    else
    {
        printf("INVALID\n");
    }
}
//Finding Length of a card for lunhs
int lengthCheck(long cardNum)
{
    int returnLength = 0;
    while (cardNum > 0)
    {
        cardNum /= 10;
        returnLength++;
    }
    return returnLength;
}
// finds the first two numbers by dividing the number by 10 to the power of the cards length minus two to get the first two.
long firstTwoNumbers(long cardNum, int cardLength)
{
    long doubles = 0;
    // selects the first two numbers by essentially removing the trailing numbers
    doubles = cardNum / pow(10, cardLength - 1);
    // If it isn't equal to 4, it isn't visa, so check again
    if (doubles != 4)
    {
        doubles = cardNum / pow(10, cardLength - 2);
    }
    return doubles;
}
// checks to see what type a card is based on length and first two numbers
char *cardCheck(long cLength, long firstTwo)
{
    switch (cLength)
    {
        // Checking the card is 15 long, and starts with 34 or 37
        case 15:
            if (firstTwo == 34 || firstTwo == 37)
            {
                return "AMEX\n";
            }
            break;
        case 13:
            return "VISA\n";
            break;
        case 16:
            if (firstTwo == 4)
            {
                return "VISA\n";
            }
            if (firstTwo >= 51 && firstTwo <= 55)
            {
                return "MASTERCARD\n";
            }
            break;
    }
    return "INVALID\n";
}
// end of finding length and make, finds how long the numbers array should be for lunhs
int obtainDispersionLength(int startIDX, int cardLength)
{
    return (startIDX == 1) ? floor((float)cardLength / 2) : ceil((float)cardLength / 2);
}
// extracts each digit one by one and puts them into an array
int *extractDigits(int cardLength, long cardNum)
{
    int *returnDoubles = SetIntDefaultValues(cardLength);//(int *) malloc(sizeof(int) * cardLength * 2);
    long cachedNumber = cardNum;
    for (int i = 0; i < cardLength; i++)
    {
        // Store the current number into the arrays index of i
        returnDoubles[i] = cachedNumber % 10;
        // Take away the currently stored number
        cachedNumber -= returnDoubles[i];
        // Divide by 10 to remove the trailing 0 (that was generated by removing its  value, example it was 5. 5-5 = 0, remove the 0 to get to the next number)
        cachedNumber /= 10;
    }
    return returnDoubles;
}
// sets all the values in an array to -999
int *SetIntDefaultValues(int length)
{
    int *newInt = (int *) malloc(sizeof(int) * length * 3);
    for (int i = 0; i < length * 2; i++)
    {
        newInt[i] = -999;
    }
    return newInt;
}
// sets all the values in an array to -999
long *SetLongDefaultValues(int length)
{
    long *newLongg = (long *) malloc(sizeof(long) * length * 3);
    for (int i = 0; i < length * 2; i++)
    {
        newLongg[i] = -999;
    }
    return newLongg;
}
// Separates the products of a set of digits
int *separateDigits(int *array)
{
    int a = 0;
    int b = 0;
    int length = 0;
    for (int i = 0; array[i] != -999; i++)
    {
        if (array[i + 1] == -999)
        {
            length = i + 1;
        }
    }
    for (int i = 0; array[i] != -999; i++)
    {
        float f = (float)array[i] / 10;
        if (f >= 1)
        {
            int floored = floor(array[i] / 10);
            int modded = array[i] % 10;
            array[i] = floored;
            array[length] = modded;
            separateDigits(array);
        }
    }
    return array;
}